on: push
name: ğŸš€ Deploy scripts on push
jobs:
  script-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v4
    
    - name: ğŸ“‚ Upload files to server
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.ftp_server }}
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        server-dir: ${{ secrets.server_dir }}